language: cpp

os:
  - linux
  - osx

compiler: 
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:boost-latest/ppa'
    packages:
    - gcc-5
    - g++-5
    - cmake
    - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  # OSX Setup 
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi

install:
  # Linux Setup 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="/usr/bin/g++-5"                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC="/usr/bin/gcc-5"                                                                ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.8.0-Linux-x86_64/bin:$PATH                                       ;fi 


script:
  - mkdir build && cd build && cmake .. && cmake --build .

